---
title: "NYC Emergency Visits"
author: "Matthew"
date: "5/19/2022"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(rvest)
library(sf)
library(tidyverse)
library(jsonlite)
library(tidycensus)
theme_set(theme_bw())
```

# Read Data
```{r}
emergencyVisits <- 
fromJSON("https://data.cityofnewyork.us/resource/2nwg-uqyg.json?$limit=3000")
```


# Part 1
## Alter date column and remove 'extract_date'
```{r}
emergencyVisits <- emergencyVisits %>% 
  mutate(date = as.POSIXct(date)) %>% 
  select(-extract_date) 
```


## Last 300 Visits
```{r}
last300 <- emergencyVisits %>% 
  arrange(desc(date)) %>% 
  head(300)
```


## Convert appropriate columns to numeric
```{r}
last300 <- last300 %>% 
  rename(ZIPCODE = mod_zcta) %>% 
  mutate(across(.cols = -c(date, ZIPCODE), as.numeric))
```


## Number of visits per zip code
```{r}
last300 %>% 
  group_by(ZIPCODE) %>% 
  summarize(total = sum(total_ed_visits)) %>% 
  arrange(-total)
```


# Part 2
```{r}
NYCmap <- st_read("C:/Users/Matthew Hondrakis/Downloads/ZIP_CODE_040114", layer = "ZIP_CODE_040114")
```


## Plot empty map
```{r}
NYCmap %>% 
  ggplot() + geom_sf() 
```


# Part 3
## Join data
```{r}
joined_data <- last300 %>% 
  inner_join(NYCmap)
```


## Colored Map by Visits
```{r}
NYCmap %>% 
  left_join(last300) %>% 
  group_by(ZIPCODE) %>% 
  mutate(total = sum(total_ed_visits)) %>% 
  ggplot(aes(fill = total)) + geom_sf() +
  scale_fill_viridis_c() + 
  labs(title = "Map of total visits", caption = "Grey shade = NA from left joining on last 300 visits") +
  theme(plot.title = element_text(hjust = 0.5))
```


# Part 4
## Census Data
```{r}
census_api_key("aa512886c5449a582d837da8d3a07af66a043fe5", install=TRUE, overwrite=T)

readRenviron("~/.Renviron")

censusData <- load_variables(2018, "acs5", cache=T)

populationData <- get_acs(geography = "zcta", variables = 'B01003_001', geometry = FALSE)

```


```{r}
populationData <- populationData %>% 
  mutate(ZIPCODE = sub("ZCTA5 ", "", NAME)) %>% 
  rename(population = estimate)
```


## Join population data with emergency visits
```{r}
pop_ed_visits <- last300 %>% 
  inner_join(populationData)
```


## Visits per inhabitant by zip code
```{r}
pop_ed_visits <- pop_ed_visits %>% 
  group_by(ZIPCODE) %>% 
  mutate(total = sum(total_ed_visits),
         ed_ratio = total_ed_visits/population)
```


# Part 5
## Poverty Dat
```{r}
vars <- c(poverty = 'B17001_002')
povertyData <- get_acs(geography = "zcta", variables = vars, geometry = FALSE)
```


