---
title: "Office"
author: "Matthew"
date: '2022-06-15'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(lubridate)
theme_set(theme_bw())
```


# Office Supplies

## Read and Clean Up
```{r}
office_supplies <- read_csv("C:/Users/Matthew Hondrakis/Downloads/office_supplies.csv")

office_supplies <- office_supplies %>% 
  rename_with(tolower) %>% 
  rename_with(~ gsub(" ", "_", .))
```


## EDA
```{r}
skimr::skim(office_supplies)

office_supplies %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + geom_histogram() + 
  facet_wrap(~key, scales = "free")
```


```{r}
office_supplies %>% 
  group_by(region) %>% 
  summarize(m = mean(profit, na.rm = TRUE)) %>% 
  arrange(-m)

office_supplies %>% 
  group_by(region, category) %>% 
  summarize(m = mean(profit, na.rm = TRUE)) %>% 
  arrange(category, -m) %>% 
  knitr::kable()

ggplot(office_supplies, aes(region, quantity)) + geom_boxplot() +
  facet_wrap(~category, scales = "free")
```



```{r}
gplot <- function(x, ...){
office_supplies %>% 
  group_by(region, ...) %>% 
  summarize(m = mean({{x}}, na.rm = TRUE)) %>% 
  slice_head(n = 6) %>% 
  ggplot(aes(m, region))
}

gplot(quantity, category) + 
  geom_col(position = "dodge", aes(fill = category))

gplot(quantity, `sub-category`) + 
  geom_col(position = "dodge", aes(fill = `sub-category`)) + 
  geom_text(aes(label = `sub-category`, group = `sub-category`), position = position_dodge(0.9), size = 3, hjust = 1.5)

gplot(quantity, product_name) + 
  geom_col(position = "dodge", aes(fill = product_name)) + theme(legend.position = "none") +
  geom_text(aes(label = product_name, group = product_name), position = position_dodge(0.9), size = 2.65, hjust = 1) 
```



```{r}
office_supplies %>% 
  ggplot(aes(order_date, sales, color = category)) + geom_line() +
  facet_wrap(~region, scales = "free")

gplot2 <- function(x){ 
  office_supplies %>%  
    ggplot(aes(order_date, {{x}})) + geom_line() +
    facet_grid(rows = vars(region), cols = vars(`sub-category`))
}

#gplot2(quantity)

```



```{r}
office_supplies %>% 
  group_by(region, `sub-category`) %>% 
  summarize(n = sum(quantity)) %>% 
  arrange(-n) %>% 
  slice_head(n = 4) %>% 
  ggplot(aes(n, fct_reorder(region, n, max), 
             fill = fct_reorder(`sub-category`, n, max))) + 
  geom_col(position = "dodge") + 
  labs(fill = "", x = "Total Quantity Sold", y = "")
```



```{r}
office_supplies %>% 
  group_by(region, product_name) %>% 
  summarize(m = sum(quantity)) %>% 
  slice_max(m, n = 5) %>% 
  ggplot(aes(m, label = product_name, 
             fct_reorder(region, m), 
             fill = fct_reorder(product_name, m, max, .desc = TRUE))) +
  geom_col(position = "dodge") + scale_fill_brewer(palette = "Paired") +
  geom_text(aes(label = `product_name`), position = position_dodge(width = 1), size = 3, hjust = 1) +
  labs(x = "Total Quantity Sold", y = "", fill = "") +
  theme(legend.position = "none")
```



```{r}
gplot3 <- function(x){
  office_supplies %>% 
    filter(region == {{x}}) %>% 
    group_by(month = month(order_date, label = TRUE), category) %>% 
    summarize(sum = sum(quantity)) %>% 
    arrange(-sum) %>% 
    slice_max(sum, n = 3) %>% 
    ggplot(aes(sum, month, fill = category)) + geom_col(position = "dodge") +
    geom_text(aes(label = sum), position = position_dodge(width = 1), size = 3, hjust = -0.3)
}
count(office_supplies, region)
( (gplot3("West") + xlim(0,1250) + labs(title = "West")) + (gplot3("East") + xlim(0,1250) + labs(title = "East"))) /
( (gplot3("Central") + xlim(0,1250) + labs(title = "Central")) + (gplot3("South") + xlim(0,1250) + labs(title = "South"))) + 
 plot_layout(guides = 'collect')
```



```{r}
office_supplies %>% 
  group_by(wday = wday(order_date, label = TRUE), category) %>% 
  summarize(sum = sum(quantity)) %>% 
  arrange(-sum) %>% 
  slice_max(sum, n = 3) %>% 
  ggplot(aes(sum, wday, label = sum, fill = fct_reorder2(category, wday, sum, .desc = FALSE))) + geom_col() +
  geom_text(color = "white", position = position_stack(vjust = 0.5), size = 3) +
  labs(fill = "", x = "Total Quantity Sold")
```




# Rstudio Cloud
```{r}
summary(aov(quantity ~ region:`sub-category`, office_supplies))

office_supplies %>% 
  ggplot(aes(`sub-category`, quantity, fill = region)) + geom_boxplot()
```


## Check Tables sold
```{r}
office_supplies %>% 
  filter(`sub-category` == "Tables") %>% 
  ggplot(aes(region, quantity)) + geom_boxplot() + geom_jitter(width = 0.25)

office_supplies %>% 
  filter(`sub-category` == "Tables") %>% 
  group_by(region) %>% 
  summarize(n = n()) %>% 
  arrange(-n)
```


```{r}
office_supplies %>%
  group_by(region, `sub-category`) %>% 
  summarize(m = mean(quantity, na.rm = TRUE),
            sd = sd(quantity, na.rm = TRUE)) %>% 
  ggplot(aes(fct_reorder(`sub-category`, m, max), m, fill = region)) +
  geom_col(position = "dodge") + 
  geom_errorbar(aes(ymin = m-sd, ymax = m+sd), width = 0.5, 
                position = position_dodge(0.9), alpha = 0.4)
```


```{r}
office_supplies %>% 
  ggplot(aes(quantity)) + geom_density()
```


```{r}
office_supplies %>% 
  group_by(month = month(order_date, label = TRUE), `sub-category`, region) %>% 
  summarize(m = mean(quantity)) %>% 
  ggplot(aes(m, `sub-category`, fill = region)) + 
  geom_col(position = "dodge") +
  facet_wrap(~month)
```


```{r}
office_supplies %>% 
  select(discount, sales, quantity) %>% 
  pivot_longer(-discount) %>% 
  ggplot(aes(discount, value)) + geom_point() +
  facet_wrap(~name, scales = "free")
```



```{r}
nested_data <- office_supplies %>% 
  mutate(month = month(order_date, label = TRUE)) %>% 
  select(region, category, `sub-category`, quantity, month) %>% 
  nest(-month) 

nested_data %>% 
  mutate(model = map(data, ~lm(quantity ~ region:`sub-category`, .x)),
         tidy = map(model, broom::tidy)) %>% 
  unnest(tidy) %>% 
  filter(term != "(Intercept)", p.value < 0.05) %>% 
  mutate(term = gsub('region|`sub-category`', '', term)) %>% 
  arrange(-abs(estimate))
```







