---
title: "Inspections"
author: "Matthew"
date: "3/16/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(lubridate)
theme_set(theme_bw())
```


```{r}
inspections <- read_csv("https://data.cityofnewyork.us/resource/43nn-pn8j.csv")
inspections <- inspections %>%
  rename(id = camis, name = dba)
```


# EDA
```{r}
inspections %>%
  filter(!is.na(score)) %>%
  summarize(min(score), max(score))

inspections %>%
  count(score, sort = TRUE)
```


## Analysis of Boroughs
```{r}
inspections %>%
  filter(!is.na(score), boro != 0) %>%
  group_by(boro) %>%
  summarize(m = mean(score)) %>%
  ggplot(aes(m, fct_reorder(boro, m), fill = boro)) + geom_col() +
  labs(y = "", fill = "")

inspections %>%
  filter(grade %in% c("A", "B", "C")) %>%
  group_by(boro) %>%
  count(grade, sort = TRUE) %>%
  ggplot(aes(n, fct_rev(grade), fill = boro)) + geom_col(position = "dodge") +
  labs(y = "", x = "Count", title = "The number of grades by borough")

inspections %>%
  filter(grade %in% c("A", "B", "C")) %>%
  group_by(boro) %>%
  summarize(A = mean(grade == "A"),
            B = mean(grade == "B"),
            C = mean(grade == "C")) %>%
  pivot_longer(-boro) %>%
  ggplot(aes(value, fct_rev(name), fill = boro)) + geom_col(position = "dodge") +
  labs(y = "", x = "Proportion") + scale_x_continuous(breaks = seq(0,1,0.1),
                                                      labels = scales::percent_format())

inspections %>%
  filter(grade %in% c("A", "B", "C")) %>%
  group_by(boro) %>%
  summarize(A = mean(grade == "A"),
            B = mean(grade == "B"),
            C = mean(grade == "C")) %>%
  pivot_longer(-boro) %>%
  ggplot(aes(value, fct_reorder(boro, value, .fun = max), fill = fct_rev(name))) + geom_col() +
  labs(y = "", x = "Proportion", fill = "") + scale_x_continuous(labels = scales::percent_format())
  
```


```{r}
inspections %>%
  filter(boro != 0, !is.na(score)) %>%
  group_by(boro, cuisine_description) %>%
  summarize(max_score = max(score)) %>%
  arrange(boro, -max_score) %>% knitr::kable()
```

