---
title: "Title"
author: "Matthew"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500, fig.showtext = TRUE)
library(tidyverse)
library(lubridate)
library(scales)
library(patchwork)
library(sysfonts)
library(showtext)
font_add_google("Roboto Slab", "Roboto")
theme_set(theme_minimal())
theme_update(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             text = element_text(family = "Roboto"))
showtext_auto()
```

```{r, message = FALSE}
data <- read_csv("~/DataAnalysis/FilteredAccidents.csv") %>% 
  rename_with(tolower)
```

```{r}
data %>% count(severity, sort = TRUE)
```

```{r}
set.seed(123)
library(tidymodels)
library(textrecipes)

splits <- initial_split(data %>% 
                          select(severity, description) %>% 
                          filter(severity %in% c(1,4)) %>% 
                          mutate(severity = factor(severity)))

training(splits) %>% count(severity)
```

```{r}
glm_workflow <- 
  recipe(formula = severity ~ description, data = training(splits)) %>% 
  step_tokenize(description) %>%
  step_stopwords(description, custom_stopword_source = stopwords::stopwords()) %>% 
  step_tokenfilter(description, max_tokens = 1e2) %>% 
  step_tfidf(description) %>% 
  workflow(logistic_reg(mode = "classification", engine = "glm"))

glm_fit <- glm_workflow %>% last_fit(splits)
```

```{r}
glm_fit %>% collect_metrics()

glm_fit %>% 
  collect_predictions() %>% 
  roc_curve(severity, .pred_1) %>% 
  autoplot()

glm_fit %>% 
  collect_predictions()  %>% 
  conf_mat(severity, .pred_class) %>% 
  autoplot(type = 'heatmap')
```

```{r}
glm_fit %>% 
  extract_fit_parsnip() %>% 
  broom::tidy() %>% 
  filter(term != "(Intercept)") %>%
  mutate(term = str_remove(term, "tfidf_description_")) %>% 
  slice_max(abs(estimate), n = 20) %>% 
  ggplot(aes(abs(estimate), fct_reorder(term, abs(estimate)), fill = ifelse(estimate < 0, "A", "B"))) + geom_col(color = "black") +
  scale_fill_discrete(direction = -1) +
  labs(fill = "Class", y = "", title = str_to_title("Importance of words in predicting class"))
```

