---
title: "Lasso-Ridge Regression"
author: "Matthew"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500, fig.showtext = TRUE)
library(tidyverse)
library(lubridate)
library(scales)
library(patchwork)
library(sysfonts)
library(showtext)
font_add_google("Roboto Slab", "Roboto")
theme_set(theme_minimal())
theme_update(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             text = element_text(family = "Roboto"))
showtext_auto()
```

# Read Data

```{r, message = FALSE}
col_names <- c(
 "CRIM", 
 "ZN", 
 "INDUS",
 "CHAS",
 "NOX",
 "RM",
 "AGE",
 "DIS",
 "RAD",
 "TAX",
 "PTRATIO",
 "B",
 "LSTAT",
 "MEDV")

data <- read.table("~/DataAnalysis/Lasso-Ridge Regression/data.txt", col.names = col_names)
```

```{r}
data_description <- data.frame(
  Variable = c("CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"),
  Description = c(
    "per capita crime rate by town",
    "proportion of residential land zoned for lots over 25,000 sq.ft.",
    "proportion of non-retail business acres per town",
    "Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)",
    "nitric oxides concentration (parts per 10 million)",
    "average number of rooms per dwelling",
    "proportion of owner-occupied units built prior to 1940",
    "weighted distances to five Boston employment centres",
    "index of accessibility to radial highways",
    "full-value property-tax rate per $10,000",
    "pupil-teacher ratio by town",
    "1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town",
    "% lower status of the population",
    "Median value of owner-occupied homes in $1000's")
)

knitr::kable(data_description)
```

# Explore

```{r}
data %>% 
  pivot_longer(-MEDV) %>% 
  group_by(name) %>% 
  summarize(corr = cor(log(MEDV), value)) %>% 
  arrange(-abs(corr)) %>% 
  ggplot(aes(abs(corr), fct_reorder(name, abs(corr)), fill = corr>0)) +
  geom_col(color = "black") +
  geom_text(aes(label = round(abs(corr), 2)), hjust = 1.2) +
  labs(y = "Variable", x = "Correlation",
       title = "Variables Correlated with Log(Price)")
```

```{r}
data %>% 
  mutate(logmdev = log(MEDV)) %>% 
  select(logmdev, LSTAT, RM, TAX) %>% 
  pivot_longer(-logmdev) %>% 
  ggplot(aes(value, logmdev)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~name, scales = "free") +
  labs(title = "Log Median Price by 3 Most Correlated") 
```

# Split Data

```{r}
library(tidymodels)

data_split <- initial_split(data, 1/2)
data_train <- training(data_split)
data_testing <- testing(data_split)
```

# Linear Regression

```{r}
rec <- recipe(MEDV ~ ., data_train) %>% 
  step_log(all_outcomes())

lm_spec <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

lm_mod <- workflow() %>% 
  add_model(lm_spec) %>% 
  add_recipe(rec) %>% 
  last_fit(data_split)

lm_mod %>% collect_metrics()
```

# Ridge Regression

```{r}
ridge_spec <- linear_reg(mixture = 0, penalty = tune()) %>% 
  set_mode("regression") %>% 
  set_engine("glmnet")

penaltygrid <- grid_regular(penalty(range = c(-3,3)), levels = 30)

ridge_wkfl <- workflow() %>% 
  add_model(ridge_spec) %>% 
  add_recipe(rec)

tune_res <- tune_grid(
  ridge_wkfl,
  resamples = vfold_cv(data_train, v = 10), 
  grid = penaltygrid
)

autoplot(tune_res)

best_p <- select_best(tune_res, metric = "rsq")

ridge_wkfl_fit <- ridge_wkfl %>% 
  finalize_workflow(best_p) %>% 
  last_fit(data_split)

ridge_wkfl_fit %>% 
  collect_metrics()
```
